name: visual-icl-3d
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - pyyaml
  - tqdm
  - pip
  - pip:
      - transformers
      - opencv-python-headless
      - matplotlib
      - seaborn
      - imageio
      - imageio[ffmpeg]